name: paymentmanagement
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  image_picker: ^0.8.5+3
  syncfusion_flutter_charts: ^20.2.39
  photo_view: ^0.14.0
  get_storage: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
